/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_myrddin_delaunay_triangulation_DelaunayTriangulation */

#ifndef _Included_fr_myrddin_delaunay_triangulation_DelaunayTriangulation
#define _Included_fr_myrddin_delaunay_triangulation_DelaunayTriangulation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_myrddin_delaunay_triangulation_DelaunayTriangulation
 * Method:    jniTriangulate
 * Signature: ([I)[I
 */
JNIEXPORT jdoubleArray JNICALL Java_fr_myrddin_delaunay_triangulation_DelaunayTriangulation_jniTriangulate
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
